resources:
  operator:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metricServer:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi

nodeSelector:
  kubernetes.io/os: linux
  workload: management

operator:
  name: keda-operator
  replicaCount: 1

metricsServer:
  replicaCount: 1

http:
  timeout: 3000
  keepAlive:
    enabled: true
  minTlsVersion: TLS12